rlslam:
  
  steps_in_episode: 200
  crash_count_thresh: 40
  
  initial_posx: 0.0
  initial_posy: 0.0
  
  obs_space_max:
    px: 3.5
    py: 2.5
    qz: inf
   
  obs_space_min:
    px: -3.5
    py: -2.5
    qz: -inf

  maze_size: 10

  scan_max_distance: 4.0
  scan_min_distance: 0.2
  training_image_size: 8
  crash_distance: 0.14
  map_completed_threshold: 106.6 # test-world-245, world-1 = 10.6632 ,w-2=10.633, w-5 = 11.652 , w-4= 10.438
  reward_map_completed: 100.
  reward_crashed: -2.

  steering: 0.8
  throttle: 0.2

  timeout: 5.0
  sleep_reset_time: 1.0
